name: Cass Config Builder Build & Deploy
on:
  push:
    branches: [ master, add-github-workflow ]
  pull_request:
    branches: [ master ]
jobs:
  build_operator_docker:
    name: Build Cass Config Builder Docker Image
    runs-on: ubuntu-latest
    env:
      GOPATH: /home/runner/go
      GOROOT: /usr/local/go1.13
    steps:
      - uses: actions/checkout@v2
        if: github.event_name != 'pull_request'
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/checkout@v2
        if: github.event_name != 'pull_request'
      - name: Set up java 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build docker image
        if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == 'datastax/cass-config-builder'
        env:
          ORG_GRADLE_PROJECT_dockerRegistry: docker.pkg.github.com
          ORG_GRADLE_PROJECT_dockerRegistryUsername: ${{ github.actor }}
          ORG_GRADLE_PROJECT_dockerRegistryPassword: ${{ secrets.GITHUB_TOKEN }}
        uses: eskatos/gradle-command-action@v1
        with:
          gradle-version: 6.0.1
          arguments: pushDockerImage
