name: Cass Config Builder Stable Build & Deploy
on:
  push:
    branches:    
      - add-github-actions
jobs:
  build_cass_config_builder_jar:
    name: Build Cass Config Builder Jar
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew assemble   
    - name: Deploy jar to artifactory
      env:
        mavenRepositoryUrlTest: "urltest"
        mavenRepositoryUrl: "url"
        mavenRepositoryUsername: "user"
        mavenRepositoryPassword: "pass"
      run: ./gradlew publish
