name: Docker Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release_config_builder:
    name: Release Cass Config Builder
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Setup Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
      - name: Cache Docker layers
        uses: actions/cache@v2
        id: cache
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Publish to Dockerhub
        run: |
          export GITHUB_REPO_URL="https://github.com/${{ github.repository }}"
          ./scripts/push-release.sh
